# Generated by Django 5.1.4 on 2026-06-25 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('WELCOME', 'Bienvenue'), ('ORDER_CONFIRM', 'Confirmation commande'), ('ORDER_STATUS', 'Changement statut'), ('ORDER_EXPIRED', 'Commande expirée'), ('OTP', 'Code OTP'), ('PASSWORD_RESET', 'Réinitialisation mot de passe'), ('LOW_STOCK', 'Stock faible'), ('PROMO', 'Promotion')], db_index=True, max_length=30)),
                ('destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('contenu_html', models.TextField()),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('erreur', models.TextField(blank=True)),
            ],
        ),
    ]
