# Generated by Django 5.1.4 on 2026-06-25 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='users.adresse'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.varianteproduit'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['user', '-created_at'], name='orders_comm_user_id_bc8890_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'date_expiration_stock'], name='orders_comm_statut_5e1f77_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='quantite_positif'),
        ),
    ]
