# Generated by Django 5.1.4 on 2026-06-25 17:42

import apps.catalog.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('PARFUM', 'Parfum'), ('COSMETIQUE', 'Cosmétique')], db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=apps.catalog.models.upload_categorie_image, validators=[apps.catalog.models.validate_image_file])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='gin_categorie_nom')],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255)),
                ('marque', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nb_avis', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalog.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=apps.catalog.models.upload_produit_image, validators=[apps.catalog.models.validate_image_file])),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.produit')),
            ],
            options={
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantePRoduit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenance_ml', models.PositiveBigIntegerField(verbose_name='Contenance (ml)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (XOF)')),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='gin_produit_search'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_26e7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['marque', 'is_active'], name='catalog_pro_marque_42ad41_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'is_active'], name='catalog_pro_categor_e78d50_idx'),
        ),
        migrations.AddIndex(
            model_name='produitimage',
            index=models.Index(fields=['produit', 'ordre'], name='catalog_pro_produit_58c0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproduit',
            index=models.Index(fields=['produit', 'is_active'], name='catalog_var_produit_9ac031_idx'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.UniqueConstraint(fields=('produit', 'contenance_ml'), name='unique_contenance_par_produit'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_positif'),
        ),
    ]
