# Generated by Django 5.1.4 on 2026-07-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_produit_slug'),
        ('catalog', '0002_search_vector_trigger'),
    ]

    operations = [
    ]
