# Generated by Django 5.1.4 on 2026-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_0002_produit_slug_0002_search_vector_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproduit',
            name='sku',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
