# Generated by Django 6.0.7 on 2026-07-10 13:36

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_varianteproduit_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='varianteproduit',
            name='contenance_ml',
            field=models.PositiveIntegerField(verbose_name='Contenance (ml)'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_b220d9_idx'),
        ),
    ]
