# Generated by Django 5.1.4 on 2026-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_reglementation_abmed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categorie',
            new_name='catalog_cat_type_04e51a_idx',
            old_name='catalog_cat_type_is_ac_idx',
        ),
        migrations.AlterField(
            model_name='produitinterdit',
            name='date_interdiction',
            field=models.DateField(help_text='Date du communiqué ABMed', verbose_name="Date d'interdiction"),
        ),
        migrations.AlterField(
            model_name='produitinterdit',
            name='motif_interdiction',
            field=models.TextField(help_text="Raison sanitaire de l'interdiction", verbose_name="Motif d'interdiction"),
        ),
        migrations.AlterField(
            model_name='produitinterdit',
            name='substance_dangereuse',
            field=models.CharField(blank=True, help_text='Ex: Corticoïdes, Hydroquinone, Mercure...', max_length=255, verbose_name='Substance dangereuse'),
        ),
        migrations.AlterField(
            model_name='signalementeffetindesirable',
            name='nom_produit_signale',
            field=models.CharField(help_text="Si le produit n'est pas dans le catalogue", max_length=255, verbose_name='Nom du produit signalé'),
        ),
        migrations.AlterField(
            model_name='signalementeffetindesirable',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', "En cours d'examen"), ('TRANSMIS_ABMED', "Transmis à l'ABMed"), ('CLOTURE', 'Clôturé')], db_index=True, default='NOUVEAU', max_length=20),
        ),
    ]
