# Generated by Django 5.1.4 on 2026-06-25 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT_FIXE', 'Montant fixe (XOF)')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.categorie')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'indexes': [models.Index(fields=['date_debut', 'date_fin', 'is_active'], name='promotions__date_de_9feb32_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('produit__isnull', False), ('categorie__isnull', False), _connector='OR'), name='promo_cible_requise'), models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='promo_dates_coherentes')],
            },
        ),
    ]
