# Generated by Django 5.1.4 on 2026-06-25 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['produit', 'is_visible'], name='reviews_avi_produit_44762f_idx'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(fields=('produit', 'user'), name='un_avis_par_user_produit'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.CheckConstraint(condition=models.Q(('note__gte', 1), ('note__lte', 5)), name='note_entre_1_et_5'),
        ),
    ]
