# Generated by Django 5.1.4 on 2026-07-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_client__fcf9c4_idx',
            old_name='chat_conver_client__a8e8a4_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_statut_2175e9_idx',
            old_name='chat_conver_statut__e6e5e0_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_agent_s_3683e8_idx',
            old_name='chat_conver_agent_s_f5b7e1_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_d0740f_idx',
            old_name='chat_messag_convers_5a1b4e_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_type_me_afb5c9_idx',
            old_name='chat_messag_type_me_8c3f2a_idx',
        ),
    ]
